### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by DarthMalloc** [nucleic/kiwi#62] opened 2019-02-27 05:15 UTC
Hi there,

I have written a program that imports kiwisolver through one of the other modules that it uses, and am trying to run it on Linux Mint 18.0. I have installed the latest version of kiwisolver from source i.e. by running python3 setup.py install. Even with kiwisolver installed, I get the following error:

Traceback (most recent call last):
  File "/home/justin/Methodology_Rotation1/Quantum_Neuron_Sim/Redfield_Simulation/redfield_test.py", line 5, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/pyplot.py", line 31, in <module>
    import matplotlib.colorbar
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/colorbar.py", line 38, in <module>
    import matplotlib.gridspec as gridspec
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/gridspec.py", line 29, in <module>
    import matplotlib._layoutbox as layoutbox
  File "/usr/local/lib/python3.5/dist-packages/matplotlib/_layoutbox.py", line 23, in <module>
    import kiwisolver as kiwi
ImportError: No module named 'kiwisolver'

Please let me know what changes I should make to setup.py in order to ensure that kiwisolver installs correctly.

Thank you very much for your help.

**Comment by MatthieuDartiailh** [comment] 2019-03-04 01:21
Are you sure you installed kiwi against the right interpreter ? (What returns `which python` ?) What happens if you start python3 and try to import manually ?

Also how did you install matplotlib ? Usually it handles kiwi installation automatically.

**Comment by MatthieuDartiailh** [comment] 2019-05-25 09:05
Closing in the absence of answer since I could not reproduce.

**Closed by MatthieuDartiailh** 2019-05-25 09:05 UTC
